launch_cmd = "cd /cluster/home/pfeene01/CCGaussian; nvidia-smi; pipenv run python ccgaussian/train_ndcc.py"

[sbatch]
-p = "ccgpu"
-t = "0-2:0:0"
--gres = "gpu:a100:1"
-c = 10
-o = "slurm_out/%A_%a.out"
